### ISSUE TITLE
Redis stops working

### ISSUE THREAD

**Issue by Thepaco777** [ProxioDev/RedisBungee#92]
Hello, these last few days I have been having problems with the redis of one of the proxies stops working and then everything breaks out of nowhere one stops working and I want to see if you can help me because it has already happened to me 4 times this week

I don't have logs because no error appears in the console

**Comment by ham1255** [comment]
What version of redis bungee you are running

**Comment by ham1255** [comment]
Seems similar to #91

**Comment by Thepaco777** [comment]
RedisBungee-Bungee-0.11.3-SNAPSHOT-all and Redis-7

**Comment by ham1255** [comment]
can you try the development branch 
https://github.com/ProxioDev/RedisBungee/tree/dev/0.12.0/update

since it has updated Jedis + new data system inside it

**Comment by Thepaco777** [comment]
Okay

**Comment by Thepaco777** [comment]
I put that version and the folder is not generated, what can I do?

**Comment by ham1255** [comment]
> I put that version and the folder is not generated, what can I do?
> 

when you compile run *./gradlew clean shadowJar* then if you use bungeecord go to folder RedisBungee-Bungee/build /libs/RedisBungee-Bungee-VERSION-all.jar

**Comment by Thepaco777** [comment]
The folder is still not generated and this error appears when turning off the proxy

[15:46:46 ERROR]: Exception disabling plugin RedisBungee
java.lang.RuntimeException: java.lang.NullPointerException: Cannot invoke "com.imaginarycode.minecraft.redisbungee.api.ProxyDataManager.close()" because "this.proxyDataManager" is null
        at com.imaginarycode.minecraft.redisbungee.RedisBungee.stop(RedisBungee.java:279) ~[?:?]
        at com.imaginarycode.minecraft.redisbungee.RedisBungee.onDisable(RedisBungee.java:316) ~[?:?]
        at net.md_5.bungee.BungeeCord.independentThreadStop(Unknown Source) ~[XCord.jar:git:Travertine-Bootstrap:1.19-R0.1-SNAPSHOT:f2b718f:unknown]
        at net.md_5.bungee.BungeeCord.access$000(Unknown Source) ~[XCord.jar:git:Travertine-Bootstrap:1.19-R0.1-SNAPSHOT:f2b718f:unknown]
        at net.md_5.bungee.BungeeCord$5.run(Unknown Source) ~[XCord.jar:git:Travertine-Bootstrap:1.19-R0.1-SNAPSHOT:f2b718f:unknown]
Caused by: java.lang.NullPointerException: Cannot invoke "com.imaginarycode.minecraft.redisbungee.api.ProxyDataManager.close()" because "this.proxyDataManager" is null
        at com.imaginarycode.minecraft.redisbungee.RedisBungee.stop(RedisBungee.java:277) ~[?:?]
        ... 4 more

**Comment by ham1255** [comment]
this error isn't useful because it shows when  plugin is disabled can you provide full logs?

**Comment by ham1255** [comment]
seems like BUILDING issue, I am not sure why @build_date@ didn't get replaced pre-compile to its value
```
[17:58:50] [main/WARN]: Exception encountered when loading plugin: RedisBungee
java.lang.ExceptionInInitializerError: null
	at com.imaginarycode.minecraft.redisbungee.RedisBungee.initialize(RedisBungee.java:196) ~[?:?]
	at com.imaginarycode.minecraft.redisbungee.RedisBungee.onEnable(RedisBungee.java:311) ~[?:?]
	at net.md_5.bungee.api.plugin.PluginManager.enablePlugins(Unknown Source) ~[XCord.jar:git:Travertine-Bootstrap:1.19-R0.1-SNAPSHOT:f2b718f:unknown]
	at net.md_5.bungee.BungeeCord.start(Unknown Source) ~[XCord.jar:git:Travertine-Bootstrap:1.19-R0.1-SNAPSHOT:f2b718f:unknown]
	at net.md_5.bungee.BungeeCordLauncher.main(Unknown Source) ~[XCord.jar:git:Travertine-Bootstrap:1.19-R0.1-SNAPSHOT:f2b718f:unknown]
	at net.md_5.bungee.Bootstrap.main(Unknown Source) ~[XCord.jar:git:Travertine-Bootstrap:1.19-R0.1-SNAPSHOT:f2b718f:unknown]
Caused by: java.lang.NumberFormatException: For input string: "@build_date@"
	at java.lang.NumberFormatException.forInputString(NumberFormatException.java:67) ~[?:?]
	at java.lang.Long.parseLong(Long.java:711) ~[?:?]
	at java.lang.Long.parseLong(Long.java:836) ~[?:?]
	at com.imaginarycode.minecraft.redisbungee.Constants.<clinit>(Constants.java:18) ~[?:?]
	... 6 more
```

anyways try download this build from 
https://github.com/ProxioDev/RedisBungee/actions/runs/8023318681

**Comment by Thepaco777** [comment]
Ok, I'll try

**Comment by Thepaco777** [comment]
[18:46:58 WARN]: Exception encountered when loading plugin: RedisBungee
com.imaginarycode.minecraft.redisbungee.internal.jedis.exceptions.JedisConnectionException: Failed to connect to any host resolved for DNS name.
        at com.imaginarycode.minecraft.redisbungee.internal.jedis.DefaultJedisSocketFactory.connectToFirstSuccessfulHost(DefaultJedisSocketFactory.java:63) ~[?:?]
        at com.imaginarycode.minecraft.redisbungee.internal.jedis.DefaultJedisSocketFactory.createSocket(DefaultJedisSocketFactory.java:89) ~[?:?]
        at com.imaginarycode.minecraft.redisbungee.internal.jedis.Connection.connect(Connection.java:194) ~[?:?]
        at com.imaginarycode.minecraft.redisbungee.internal.jedis.Connection.initializeFromClientConfig(Connection.java:392) ~[?:?]
        at com.imaginarycode.minecraft.redisbungee.internal.jedis.Connection.<init>(Connection.java:67) ~[?:?]
        at com.imaginarycode.minecraft.redisbungee.internal.jedis.ConnectionFactory.makeObject(ConnectionFactory.java:59) ~[?:?]
        at com.imaginarycode.minecraft.redisbungee.internal.commonspool2.impl.GenericObjectPool.create(GenericObjectPool.java:566) ~[?:?]
        at com.imaginarycode.minecraft.redisbungee.internal.commonspool2.impl.GenericObjectPool.borrowObject(GenericObjectPool.java:306) ~[?:?]
        at com.imaginarycode.minecraft.redisbungee.internal.commonspool2.impl.GenericObjectPool.borrowObject(GenericObjectPool.java:233) ~[?:?]
        at com.imaginarycode.minecraft.redisbungee.internal.jedis.util.Pool.getResource(Pool.java:38) ~[?:?]
        at com.imaginarycode.minecraft.redisbungee.internal.jedis.ConnectionPool.getResource(ConnectionPool.java:29) ~[?:?]
        at com.imaginarycode.minecraft.redisbungee.internal.jedis.ConnectionPool.getResource(ConnectionPool.java:7) ~[?:?]
        at com.imaginarycode.minecraft.redisbungee.internal.jedis.providers.PooledConnectionProvider.getConnection(PooledConnectionProvider.java:68) ~[?:?]
        at com.imaginarycode.minecraft.redisbungee.internal.jedis.executors.DefaultCommandExecutor.executeCommand(DefaultCommandExecutor.java:23) ~[?:?]
        at com.imaginarycode.minecraft.redisbungee.internal.jedis.UnifiedJedis.executeCommand(UnifiedJedis.java:250) ~[?:?]
        at com.imaginarycode.minecraft.redisbungee.internal.jedis.UnifiedJedis.set(UnifiedJedis.java:718) ~[?:?]
        at com.imaginarycode.minecraft.redisbungee.api.summoners.JedisPooledSummoner.<init>(JedisPooledSummoner.java:37) ~[?:?]
        at com.imaginarycode.minecraft.redisbungee.api.config.loaders.ConfigLoader.loadConfig(ConfigLoader.java:131) ~[?:?]
        at com.imaginarycode.minecraft.redisbungee.RedisBungee.initialize(RedisBungee.java:210) ~[?:?]
        at com.imaginarycode.minecraft.redisbungee.RedisBungee.onEnable(RedisBungee.java:306) ~[?:?]
        at net.md_5.bungee.api.plugin.PluginManager.enablePlugins(Unknown Source) ~[XCord.jar:git:Travertine-Bootstrap:1.19-R0.1-SNAPSHOT:f2b718f:unknown]
        at net.md_5.bungee.BungeeCord.start(Unknown Source) ~[XCord.jar:git:Travertine-Bootstrap:1.19-R0.1-SNAPSHOT:f2b718f:unknown]
        at net.md_5.bungee.BungeeCordLauncher.main(Unknown Source) ~[XCord.jar:git:Travertine-Bootstrap:1.19-R0.1-SNAPSHOT:f2b718f:unknown]
        at net.md_5.bungee.Bootstrap.main(Unknown Source) ~[XCord.jar:git:Travertine-Bootstrap:1.19-R0.1-SNAPSHOT:f2b718f:unknown]
        Suppressed: java.net.ConnectException: Connection refused
                at sun.nio.ch.Net.pollConnect(Native Method) ~[?:?]
                at sun.nio.ch.Net.pollConnectNow(Net.java:672) ~[?:?]
                at sun.nio.ch.NioSocketImpl.timedFinishConnect(NioSocketImpl.java:547) ~[?:?]
                at sun.nio.ch.NioSocketImpl.connect(NioSocketImpl.java:602) ~[?:?]
                at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:327) ~[?:?]
                at java.net.Socket.connect(Socket.java:633) ~[?:?]
                at com.imaginarycode.minecraft.redisbungee.internal.jedis.DefaultJedisSocketFactory.connectToFirstSuccessfulHost(DefaultJedisSocketFactory.java:75) ~[?:?]
                at com.imaginarycode.minecraft.redisbungee.internal.jedis.DefaultJedisSocketFactory.createSocket(DefaultJedisSocketFactory.java:89) ~[?:?]
                at com.imaginarycode.minecraft.redisbungee.internal.jedis.Connection.connect(Connection.java:194) ~[?:?]
                at com.imaginarycode.minecraft.redisbungee.internal.jedis.Connection.initializeFromClientConfig(Connection.java:392) ~[?:?]
                at com.imaginarycode.minecraft.redisbungee.internal.jedis.Connection.<init>(Connection.java:67) ~[?:?]
                at com.imaginarycode.minecraft.redisbungee.internal.jedis.ConnectionFactory.makeObject(ConnectionFactory.java:59) ~[?:?]
                at com.imaginarycode.minecraft.redisbungee.internal.commonspool2.impl.GenericObjectPool.create(GenericObjectPool.java:566) ~[?:?]
                at com.imaginarycode.minecraft.redisbungee.internal.commonspool2.impl.GenericObjectPool.borrowObject(GenericObjectPool.java:306) ~[?:?]
                at com.imaginarycode.minecraft.redisbungee.internal.commonspool2.impl.GenericObjectPool.borrowObject(GenericObjectPool.java:233) ~[?:?]
                at com.imaginarycode.minecraft.redisbungee.internal.jedis.util.Pool.getResource(Pool.java:38) ~[?:?]
                at com.imaginarycode.minecraft.redisbungee.internal.jedis.ConnectionPool.getResource(ConnectionPool.java:29) ~[?:?]
                at com.imaginarycode.minecraft.redisbungee.internal.jedis.ConnectionPool.getResource(ConnectionPool.java:7) ~[?:?]
                at com.imaginarycode.minecraft.redisbungee.internal.jedis.providers.PooledConnectionProvider.getConnection(PooledConnectionProvider.java:68) ~[?:?]
                at com.imaginarycode.minecraft.redisbungee.internal.jedis.executors.DefaultCommandExecutor.executeCommand(DefaultCommandExecutor.java:23) ~[?:?]
                at com.imaginarycode.minecraft.redisbungee.internal.jedis.UnifiedJedis.executeCommand(UnifiedJedis.java:250) ~[?:?]
                at com.imaginarycode.minecraft.redisbungee.internal.jedis.UnifiedJedis.set(UnifiedJedis.java:718) ~[?:?]
                at com.imaginarycode.minecraft.redisbungee.api.summoners.JedisPooledSummoner.<init>(JedisPooledSummoner.java:37) ~[?:?]
                at com.imaginarycode.minecraft.redisbungee.api.config.loaders.ConfigLoader.loadConfig(ConfigLoader.java:131) ~[?:?]
                at com.imaginarycode.minecraft.redisbungee.RedisBungee.initialize(RedisBungee.java:210) ~[?:?]
                at com.imaginarycode.minecraft.redisbungee.RedisBungee.onEnable(RedisBungee.java:306) ~[?:?]
                at net.md_5.bungee.api.plugin.PluginManager.enablePlugins(Unknown Source) ~[XCord.jar:git:Travertine-Bootstrap:1.19-R0.1-SNAPSHOT:f2b718f:unknown]
                at net.md_5.bungee.BungeeCord.start(Unknown Source) ~[XCord.jar:git:Travertine-Bootstrap:1.19-R0.1-SNAPSHOT:f2b718f:unknown]
                at net.md_5.bungee.BungeeCordLauncher.main(Unknown Source) ~[XCord.jar:git:Travertine-Bootstrap:1.19-R0.1-SNAPSHOT:f2b718f:unknown]
                at net.md_5.bungee.Bootstrap.main(Unknown Source) ~[XCord.jar:git:Travertine-Bootstrap:1.19-R0.1-SNAPSHOT:f2b718f:unknown]

**Comment by Thepaco777** [comment]
The folder was generated but only with the config.yml and not the other message file and that error appears

**Comment by ham1255** [comment]
on development branch config file version changed you have to redo your config

**Comment by Thepaco777** [comment]
from the redis server?

**Comment by ham1255** [comment]
not the redis server, 

config of redisbungee on 0.12.0 has changed which resets the config file with backup stored in the BACKUP folder inside redisbungee plugin folder


also https://github.com/ProxioDev/RedisBungee/actions/runs/8023929440 try this build because config versioning issue

**Comment by Thepaco777** [comment]
[19:21:11 INFO] [RedisBungee]: Initializing RedisBungee.....
[19:21:11 INFO] [RedisBungee]: Version: 0.12.0-SNAPSHOT
[19:21:11 INFO] [RedisBungee]: Build date: 2024-02-23T19:11:50.000+0000
[19:21:11 INFO] [RedisBungee]: Loaded proxy id Proxy-Devs
[19:21:11 INFO] [RedisBungee]: handle reconnect to last server: false
[19:21:11 INFO] [RedisBungee]: handle motd: true
[19:21:11 INFO] [RedisBungee]: RedisBungee MODE: SINGLE
[19:21:11 INFO] [RedisBungee]: Successfully connected to Redis.
[19:21:12 INFO] [RedisBungee]: Redis server version: 7.0.11
[19:21:12 ERROR] [RedisBungee]: Your version of Redis (7.0.11) is not at least version 3.0 RedisBungee requires a newer version of Redis.
[19:21:12 WARN]: Exception encountered when loading plugin: RedisBungee
java.lang.RuntimeException: Unsupported Redis version detected
        at com.imaginarycode.minecraft.redisbungee.api.util.InitialUtils$1.unifiedJedisTask(InitialUtils.java:33) ~[?:?]
        at com.imaginarycode.minecraft.redisbungee.api.util.InitialUtils$1.unifiedJedisTask(InitialUtils.java:22) ~[?:?]
        at com.imaginarycode.minecraft.redisbungee.api.tasks.RedisTask.execute(RedisTask.java:59) ~[?:?]
        at com.imaginarycode.minecraft.redisbungee.api.util.InitialUtils.checkRedisVersion(InitialUtils.java:44) ~[?:?]
        at com.imaginarycode.minecraft.redisbungee.RedisBungee.initialize(RedisBungee.java:246) ~[?:?]
        at com.imaginarycode.minecraft.redisbungee.RedisBungee.onEnable(RedisBungee.java:306) ~[?:?]
        at net.md_5.bungee.api.plugin.PluginManager.enablePlugins(Unknown Source) ~[XCord.jar:git:Travertine-Bootstrap:1.19-R0.1-SNAPSHOT:f2b718f:unknown]
        at net.md_5.bungee.BungeeCord.start(Unknown Source) ~[XCord.jar:git:Travertine-Bootstrap:1.19-R0.1-SNAPSHOT:f2b718f:unknown]
        at net.md_5.bungee.BungeeCordLauncher.main(Unknown Source) ~[XCord.jar:git:Travertine-Bootstrap:1.19-R0.1-SNAPSHOT:f2b718f:unknown]
        at net.md_5.bungee.Bootstrap.main(Unknown Source) ~[XCord.jar:git:Travertine-Bootstrap:1.19-R0.1-SNAPSHOT:f2b718f:unknown]

**Comment by ham1255** [comment]
fixed that issue Try this build https://github.com/ProxioDev/RedisBungee/actions/runs/8024457325

> [19:21:11 INFO] [RedisBungee]: Initializing RedisBungee..... [19:21:11 INFO] [RedisBungee]: Version: 0.12.0-SNAPSHOT [19:21:11 INFO] [RedisBungee]: Build date: 2024-02-23T19:11:50.000+0000 [19:21:11 INFO] [RedisBungee]: Loaded proxy id Proxy-Devs [19:21:11 INFO] [RedisBungee]: handle reconnect to last server: false [19:21:11 INFO] [RedisBungee]: handle motd: true [19:21:11 INFO] [RedisBungee]: RedisBungee MODE: SINGLE [19:21:11 INFO] [RedisBungee]: Successfully connected to Redis. [19:21:12 INFO] [RedisBungee]: Redis server version: 7.0.11 [19:21:12 ERROR] [RedisBungee]: Your version of Redis (7.0.11) is not at least version 3.0 RedisBungee requires a newer version of Redis. [19:21:12 WARN]: Exception encountered when loading plugin: RedisBungee java.lang.RuntimeException: Unsupported Redis version detected at com.imaginarycode.minecraft.redisbungee.api.util.InitialUtils$1.unifiedJedisTask(InitialUtils.java:33) ~[?:?] at com.imaginarycode.minecraft.redisbungee.api.util.InitialUtils$1.unifiedJedisTask(InitialUtils.java:22) ~[?:?] at com.imaginarycode.minecraft.redisbungee.api.tasks.RedisTask.execute(RedisTask.java:59) ~[?:?] at com.imaginarycode.minecraft.redisbungee.api.util.InitialUtils.checkRedisVersion(InitialUtils.java:44) ~[?:?] at com.imaginarycode.minecraft.redisbungee.RedisBungee.initialize(RedisBungee.java:246) ~[?:?] at com.imaginarycode.minecraft.redisbungee.RedisBungee.onEnable(RedisBungee.java:306) ~[?:?] at net.md_5.bungee.api.plugin.PluginManager.enablePlugins(Unknown Source) ~[XCord.jar:git:Travertine-Bootstrap:1.19-R0.1-SNAPSHOT:f2b718f:unknown] at net.md_5.bungee.BungeeCord.start(Unknown Source) ~[XCord.jar:git:Travertine-Bootstrap:1.19-R0.1-SNAPSHOT:f2b718f:unknown] at net.md_5.bungee.BungeeCordLauncher.main(Unknown Source) ~[XCord.jar:git:Travertine-Bootstrap:1.19-R0.1-SNAPSHOT:f2b718f:unknown] at net.md_5.bungee.Bootstrap.main(Unknown Source) ~[XCord.jar:git:Travertine-Bootstrap:1.19-R0.1-SNAPSHOT:f2b718f:unknown]

**Comment by Thepaco777** [comment]
Ok, I'll try

**Comment by Thepaco777** [comment]
[21:18:31 WARN]: Exception encountered when loading plugin: RedisBungee
com.imaginarycode.minecraft.redisbungee.internal.jedis.exceptions.JedisConnectionException: java.net.SocketTimeoutException: Read timed out
        at com.imaginarycode.minecraft.redisbungee.internal.jedis.Connection.flush(Connection.java:340) ~[?:?]
        at com.imaginarycode.minecraft.redisbungee.internal.jedis.Connection.getStatusCodeReply(Connection.java:267) ~[?:?]
        at com.imaginarycode.minecraft.redisbungee.internal.jedis.Connection.helloOrAuth(Connection.java:492) ~[?:?]
        at com.imaginarycode.minecraft.redisbungee.internal.jedis.Connection.initializeFromClientConfig(Connection.java:401) ~[?:?]
        at com.imaginarycode.minecraft.redisbungee.internal.jedis.Connection.<init>(Connection.java:67) ~[?:?]
        at com.imaginarycode.minecraft.redisbungee.internal.jedis.ConnectionFactory.makeObject(ConnectionFactory.java:59) ~[?:?]
        at com.imaginarycode.minecraft.redisbungee.internal.commonspool2.impl.GenericObjectPool.create(GenericObjectPool.java:566) ~[?:?]
        at com.imaginarycode.minecraft.redisbungee.internal.commonspool2.impl.GenericObjectPool.borrowObject(GenericObjectPool.java:306) ~[?:?]
        at com.imaginarycode.minecraft.redisbungee.internal.commonspool2.impl.GenericObjectPool.borrowObject(GenericObjectPool.java:233) ~[?:?]
        at com.imaginarycode.minecraft.redisbungee.internal.jedis.util.Pool.getResource(Pool.java:38) ~[?:?]
        at com.imaginarycode.minecraft.redisbungee.internal.jedis.ConnectionPool.getResource(ConnectionPool.java:29) ~[?:?]
        at com.imaginarycode.minecraft.redisbungee.internal.jedis.ConnectionPool.getResource(ConnectionPool.java:7) ~[?:?]
        at com.imaginarycode.minecraft.redisbungee.internal.jedis.providers.PooledConnectionProvider.getConnection(PooledConnectionProvider.java:68) ~[?:?]
        at com.imaginarycode.minecraft.redisbungee.internal.jedis.executors.DefaultCommandExecutor.executeCommand(DefaultCommandExecutor.java:23) ~[?:?]
        at com.imaginarycode.minecraft.redisbungee.internal.jedis.UnifiedJedis.executeCommand(UnifiedJedis.java:250) ~[?:?]
        at com.imaginarycode.minecraft.redisbungee.internal.jedis.UnifiedJedis.set(UnifiedJedis.java:718) ~[?:?]
        at com.imaginarycode.minecraft.redisbungee.api.summoners.JedisPooledSummoner.<init>(JedisPooledSummoner.java:37) ~[?:?]
        at com.imaginarycode.minecraft.redisbungee.api.config.loaders.ConfigLoader.loadConfig(ConfigLoader.java:131) ~[?:?]
        at com.imaginarycode.minecraft.redisbungee.RedisBungee.initialize(RedisBungee.java:210) ~[?:?]
        at com.imaginarycode.minecraft.redisbungee.RedisBungee.onEnable(RedisBungee.java:306) ~[?:?]
        at net.md_5.bungee.api.plugin.PluginManager.enablePlugins(Unknown Source) ~[XCord.jar:git:Travertine-Bootstrap:1.19-R0.1-SNAPSHOT:f2b718f:unknown]
        at net.md_5.bungee.BungeeCord.start(Unknown Source) ~[XCord.jar:git:Travertine-Bootstrap:1.19-R0.1-SNAPSHOT:f2b718f:unknown]
        at net.md_5.bungee.BungeeCordLauncher.main(Unknown Source) ~[XCord.jar:git:Travertine-Bootstrap:1.19-R0.1-SNAPSHOT:f2b718f:unknown]
        at net.md_5.bungee.Bootstrap.main(Unknown Source) ~[XCord.jar:git:Travertine-Bootstrap:1.19-R0.1-SNAPSHOT:f2b718f:unknown]
Caused by: java.net.SocketTimeoutException: Read timed out
        at sun.nio.ch.NioSocketImpl.timedRead(NioSocketImpl.java:288) ~[?:?]
        at sun.nio.ch.NioSocketImpl.implRead(NioSocketImpl.java:314) ~[?:?]
        at sun.nio.ch.NioSocketImpl.read(NioSocketImpl.java:355) ~[?:?]
        at sun.nio.ch.NioSocketImpl$1.read(NioSocketImpl.java:808) ~[?:?]
        at java.net.Socket$SocketInputStream.read(Socket.java:966) ~[?:?]
        at sun.security.ssl.SSLSocketInputRecord.read(SSLSocketInputRecord.java:484) ~[?:?]
        at sun.security.ssl.SSLSocketInputRecord.readHeader(SSLSocketInputRecord.java:478) ~[?:?]
        at sun.security.ssl.SSLSocketInputRecord.decode(SSLSocketInputRecord.java:160) ~[?:?]
        at sun.security.ssl.SSLTransport.decode(SSLTransport.java:111) ~[?:?]
        at sun.security.ssl.SSLSocketImpl.decode(SSLSocketImpl.java:1510) ~[?:?]
        at sun.security.ssl.SSLSocketImpl.readHandshakeRecord(SSLSocketImpl.java:1425) ~[?:?]
        at sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:455) ~[?:?]
        at sun.security.ssl.SSLSocketImpl.ensureNegotiated(SSLSocketImpl.java:925) ~[?:?]
        at sun.security.ssl.SSLSocketImpl$AppOutputStream.write(SSLSocketImpl.java:1295) ~[?:?]
        at com.imaginarycode.minecraft.redisbungee.internal.jedis.util.RedisOutputStream.flushBuffer(RedisOutputStream.java:57) ~[?:?]
        at com.imaginarycode.minecraft.redisbungee.internal.jedis.util.RedisOutputStream.flush(RedisOutputStream.java:138) ~[?:?]
        at com.imaginarycode.minecraft.redisbungee.internal.jedis.Connection.flush(Connection.java:337) ~[?:?]
        ... 23 more

**Comment by Thepaco777** [comment]
No, that was an error, I put the ssl Sorry, but it still doesn't work, I'm in the dev proxy tested with the same redis as the normal server but the people in the devs don't appear

**Comment by ham1255** [comment]
> ![image](https://private-user-images.githubusercontent.com/86302736/307471895-8d53e125-311c-44b9-be2b-6de160f6833f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDg3MzAyMjAsIm5iZiI6MTcwODcyOTkyMCwicGF0aCI6Ii84NjMwMjczNi8zMDc0NzE4OTUtOGQ1M2UxMjUtMzExYy00NGI5LWJlMmItNmRlMTYwZjY4MzNmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMjMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjIzVDIzMTIwMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWU1MjQyYWI2ZjBhOGZiMTE3MjI2MjcxNmIxMDBmNTQ5YmM3MGNhMzgzYmRkNTBhNTk5MTBiNmFhYmUwM2U0NjAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.uU_rChlJXTntMTCuMAjLdznfm-CFcAec7j-ssp1aqH0)

if you seen last messages, this development branch that has new data system its event based which can't see old format you have to apply it to all proxies #86

**Comment by ham1255** [comment]
> [21:18:31 WARN]: Exception encountered when loading plugin: RedisBungee com.imaginarycode.minecraft.redisbungee.internal.jedis.exceptions.JedisConnectionException: java.net.SocketTimeoutException: Read timed out at com.imaginarycode.minecraft.redisbungee.internal.jedis.Connection.flush(Connection.java:340) ~[?:?] at com.imaginarycode.minecraft.redisbungee.internal.jedis.Connection.getStatusCodeReply(Connection.java:267) ~[?:?] at com.imaginarycode.minecraft.redisbungee.internal.jedis.Connection.helloOrAuth(Connection.java:492) ~[?:?] at com.imaginarycode.minecraft.redisbungee.internal.jedis.Connection.initializeFromClientConfig(Connection.java:401) ~[?:?] at com.imaginarycode.minecraft.redisbungee.internal.jedis.Connection.(Connection.java:67) ~[?:?] at com.imaginarycode.minecraft.redisbungee.internal.jedis.ConnectionFactory.makeObject(ConnectionFactory.java:59) ~[?:?] at com.imaginarycode.minecraft.redisbungee.internal.commonspool2.impl.GenericObjectPool.create(GenericObjectPool.java:566) ~[?:?] at com.imaginarycode.minecraft.redisbungee.internal.commonspool2.impl.GenericObjectPool.borrowObject(GenericObjectPool.java:306) ~[?:?] at com.imaginarycode.minecraft.redisbungee.internal.commonspool2.impl.GenericObjectPool.borrowObject(GenericObjectPool.java:233) ~[?:?] at com.imaginarycode.minecraft.redisbungee.internal.jedis.util.Pool.getResource(Pool.java:38) ~[?:?] at com.imaginarycode.minecraft.redisbungee.internal.jedis.ConnectionPool.getResource(ConnectionPool.java:29) ~[?:?] at com.imaginarycode.minecraft.redisbungee.internal.jedis.ConnectionPool.getResource(ConnectionPool.java:7) ~[?:?] at com.imaginarycode.minecraft.redisbungee.internal.jedis.providers.PooledConnectionProvider.getConnection(PooledConnectionProvider.java:68) ~[?:?] at com.imaginarycode.minecraft.redisbungee.internal.jedis.executors.DefaultCommandExecutor.executeCommand(DefaultCommandExecutor.java:23) ~[?:?] at com.imaginarycode.minecraft.redisbungee.internal.jedis.UnifiedJedis.executeCommand(UnifiedJedis.java:250) ~[?:?] at com.imaginarycode.minecraft.redisbungee.internal.jedis.UnifiedJedis.set(UnifiedJedis.java:718) ~[?:?] at com.imaginarycode.minecraft.redisbungee.api.summoners.JedisPooledSummoner.(JedisPooledSummoner.java:37) ~[?:?] at com.imaginarycode.minecraft.redisbungee.api.config.loaders.ConfigLoader.loadConfig(ConfigLoader.java:131) ~[?:?] at com.imaginarycode.minecraft.redisbungee.RedisBungee.initialize(RedisBungee.java:210) ~[?:?] at com.imaginarycode.minecraft.redisbungee.RedisBungee.onEnable(RedisBungee.java:306) ~[?:?] at net.md_5.bungee.api.plugin.PluginManager.enablePlugins(Unknown Source) ~[XCord.jar:git:Travertine-Bootstrap:1.19-R0.1-SNAPSHOT:f2b718f:unknown] at net.md_5.bungee.BungeeCord.start(Unknown Source) ~[XCord.jar:git:Travertine-Bootstrap:1.19-R0.1-SNAPSHOT:f2b718f:unknown] at net.md_5.bungee.BungeeCordLauncher.main(Unknown Source) ~[XCord.jar:git:Travertine-Bootstrap:1.19-R0.1-SNAPSHOT:f2b718f:unknown] at net.md_5.bungee.Bootstrap.main(Unknown Source) ~[XCord.jar:git:Travertine-Bootstrap:1.19-R0.1-SNAPSHOT:f2b718f:unknown] Caused by: java.net.SocketTimeoutException: Read timed out at sun.nio.ch.NioSocketImpl.timedRead(NioSocketImpl.java:288) ~[?:?] at sun.nio.ch.NioSocketImpl.implRead(NioSocketImpl.java:314) ~[?:?] at sun.nio.ch.NioSocketImpl.read(NioSocketImpl.java:355) ~[?:?] at sun.nio.ch.NioSocketImpl$1.read(NioSocketImpl.java:808) ~[?:?] at java.net.Socket$SocketInputStream.read(Socket.java:966) ~[?:?] at sun.security.ssl.SSLSocketInputRecord.read(SSLSocketInputRecord.java:484) ~[?:?] at sun.security.ssl.SSLSocketInputRecord.readHeader(SSLSocketInputRecord.java:478) ~[?:?] at sun.security.ssl.SSLSocketInputRecord.decode(SSLSocketInputRecord.java:160) ~[?:?] at sun.security.ssl.SSLTransport.decode(SSLTransport.java:111) ~[?:?] at sun.security.ssl.SSLSocketImpl.decode(SSLSocketImpl.java:1510) ~[?:?] at sun.security.ssl.SSLSocketImpl.readHandshakeRecord(SSLSocketImpl.java:1425) ~[?:?] at sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:455) ~[?:?] at sun.security.ssl.SSLSocketImpl.ensureNegotiated(SSLSocketImpl.java:925) ~[?:?] at sun.security.ssl.SSLSocketImpl$AppOutputStream.write(SSLSocketImpl.java:1295) ~[?:?] at com.imaginarycode.minecraft.redisbungee.internal.jedis.util.RedisOutputStream.flushBuffer(RedisOutputStream.java:57) ~[?:?] at com.imaginarycode.minecraft.redisbungee.internal.jedis.util.RedisOutputStream.flush(RedisOutputStream.java:138) ~[?:?] at com.imaginarycode.minecraft.redisbungee.internal.jedis.Connection.flush(Connection.java:337) ~[?:?] ... 23 more

generally any error related to socket time out or connection refused is probably your connection is bad to the redis server or wrong configuration etc

**Comment by Thepaco777** [comment]
I was able to fix that, what happens to me is the last thing I said below

**Comment by ham1255** [comment]
> I was able to fix that, what happens to me is the last thing I said below

?

**Comment by Thepaco777** [comment]
> No, that was an error, I put the ssl Sorry, but it still doesn't work, I'm in the dev proxy tested with the same redis as the normal server but the people in the devs don't appear

this

**Comment by ham1255** [comment]
> > ![image](https://private-user-images.githubusercontent.com/86302736/307471895-8d53e125-311c-44b9-be2b-6de160f6833f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDg3MzAyMjAsIm5iZiI6MTcwODcyOTkyMCwicGF0aCI6Ii84NjMwMjczNi8zMDc0NzE4OTUtOGQ1M2UxMjUtMzExYy00NGI5LWJlMmItNmRlMTYwZjY4MzNmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMjMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjIzVDIzMTIwMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWU1MjQyYWI2ZjBhOGZiMTE3MjI2MjcxNmIxMDBmNTQ5YmM3MGNhMzgzYmRkNTBhNTk5MTBiNmFhYmUwM2U0NjAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.uU_rChlJXTntMTCuMAjLdznfm-CFcAec7j-ssp1aqH0)
> 
> if you seen last messages, this development branch that has new data system its event based which can't see old format you have to apply it to all proxies #86

like i said above you have to update all proxies because development branch for 0.12.0 can't see proxies on 0.11.x or lower due the new data format

**Comment by Thepaco777** [comment]
ok this afternoon I'll change it and if something doesn't go right or something happens I'll let you know.

**Comment by ham1255** [comment]
Hey, it been 2 days i think since we talked how is it going? any crashes or bugs? also might credit your server for using 0.12.0 data system in production.

**Comment by Thepaco777** [comment]
For now everything works fine, if nothing happens in a few days I will close the issue and thank you very much for the help

**Comment by ham1255** [comment]
> For now everything works fine, if nothing happens in a few days I will close the issue and thank you very much for the help

No need to close it, after 0.12.0 branch get merged i will it will close itself

**Comment by Thepaco777** [comment]
a okay

**Comment by Thepaco777** [comment]
> Hey, it been 2 days i think since we talked how is it going? any crashes or bugs? also might credit your server for using 0.12.0 data system in production. When 0.12.0 get released

If you want, this is the IP of my server -  summoncraft.us

**Comment by Thepaco777** [comment]
I've been using it for a week and it works very well, thank you very much for the help

**Comment by Thepaco777** [comment]
Hello again xd, Is it normal that this keeps appearing all the time in the proxy console?
![image](https://github.com/ProxioDev/RedisBungee/assets/86302736/afec9037-b32b-4d70-a5a1-b35b38ac72a5)
![image](https://github.com/ProxioDev/RedisBungee/assets/86302736/5fd0c4c9-e26d-4c29-b5d6-22a0c32a689d)
![image](https://github.com/ProxioDev/RedisBungee/assets/86302736/6d91bcdf-301b-4146-ac3d-5dedff892d35)
![image](https://github.com/ProxioDev/RedisBungee/assets/86302736/4c6fcb48-c476-42a6-a0a0-caa52754f2a9)

They disconnect but the other proxies are working

**Comment by Thepaco777** [comment]
![image](https://github.com/ProxioDev/RedisBungee/assets/86302736/7b696fc7-5b08-4b55-9b15-83fb6607a687)

**Comment by Thepaco777** [comment]
1 okay - https://mclo.gs/oPSl10P
2 They are in the same country
3 Bedrock users

**Comment by ham1255** [comment]
> 1 okay - https://mclo.gs/oPSl10P 2 They are in the same country 3 Bedrock users

what i mean here is time in sync? like 10~ seconds difference can cause issue

**Comment by Thepaco777** [comment]
wtf I'm going to check something, on one machine it is 5:50 p.m. and on another machine it is 1:50 p.m. and they are almost in the same place, both are in New York

**Comment by Thepaco777** [comment]
bn it's already fixed, thanks for the help xd
